### ISSUE TITLE
Fix mobile content visibility

### ISSUE THREAD

**Issue by pwflint** [pwflint/CV#25]
To ensure the `main` content begins below the fixed header in a mobile view, the issue likely lies in how the `margin-top` or padding for `main` is calculated and applied in the `@media (max-width: 768px)` query. Based on the provided `index.html`, the following adjustments can be made:

### Suggested Fix:
Update the `@media (max-width: 768px)` styles as follows:

1. **Remove the `margin-top: 0` from `main` and ensure it accounts for the fixed header height.**  
   Replace:
   ```css
   main {
       margin-top: 0;
   }
   ```
   With:
   ```css
   main {
       margin-top: var(--header-height);
   }
   ```

2. **Ensure that `main` is positioned correctly with respect to the fixed header.**  
   If the `main` content overlaps the header, this will prevent such issues.

3. **Check `body.nav-open` behavior for consistency in mobile view.**  
   When the navigation is toggled, ensure the changes do not affect `main`. Verify that toggling the navigation does not alter the `margin-top` of `main`.

4. **Verify `scroll-margin-top` for headings inside `main`.**  
   If `scroll-margin-top` is already equal to `var(--header-height)` in:
   ```css
   section[id],
   main h1[id],
   main h2[id] {
       scroll-margin-top: var(--header-height);
   }
   ```
   There's no need to adjust this further.

### Why This Fix Works
- **`margin-top` alignment:** Adding `margin-top: var(--header-height)` ensures the `main` content always starts below the fixed header.
- **Consistent spacing:** The `var(--header-height)` variable is already defined and dynamically adjusts based on the header height.

Apply this fix to your stylesheet and test it on different mobile devices to confirm proper alignment. Let me know if you need further assistance!
